
package tallermecanico;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


public class AdministrarUsuarios extends javax.swing.JInternalFrame {
    BaseDeDatos conexion = new BaseDeDatos();
    
  
    
    public AdministrarUsuarios() {
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnInsertarBorrar = new javax.swing.JToggleButton();
        txtNombre = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JToggleButton();
        txtPassword = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        btnActualizarBorrar = new javax.swing.JToggleButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();

        setClosable(true);
        setTitle("Modificar usuarios por Administrador");

        btnInsertarBorrar.setText("Insertar");
        btnInsertarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarBorrarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnActualizarBorrar.setText("Actualizar");
        btnActualizarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarBorrarActionPerformed(evt);
            }
        });

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Admin", "Cliente", "Empleado", "Visita" }));

        jLabel1.setText("Nombre");

        jLabel2.setText("Id");

        jLabel3.setText("Apellido");

        jLabel4.setText(" Usuario");

        jLabel5.setText("Contraseña");

        jLabel6.setText("Tipo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnInsertarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnActualizarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUsuarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarBorrarActionPerformed
        // TODO add your handling code here:

        if(txtId.getText().isEmpty()||txtNombre.getText().isEmpty()||txtApellido.getText().isEmpty()||
            txtUsername.getText().isEmpty()||txtPassword.getText().isEmpty()||cmbTipo.getSelectedIndex()==0){

            JOptionPane.showMessageDialog(null, "Error faltan datos por agregar");
        }else{
            int id = Integer.parseInt(txtId.getText().trim());
            String primerNombre = txtNombre.getText().trim();
            String apellido = txtApellido.getText().trim();
            String username = txtUsername.getText().trim();            
            String password = txtPassword.getText().trim();
            String tipo =cmbTipo.getSelectedItem().toString().trim() ;

            try{
                Statement statement  = conexion.conexionUsuarioDB().createStatement();
//                String query = "INSERT INTO estudiante (idEstudiante,primerNombre,apellido,email,genero,direccionIP)"
//                +"VALUES("+idEstudiante+",'"+primerNombre+"','"+apellido+"','"+email+"','"+genero+"','"+direccionIP+"')";

                 String query ="INSERT INTO LogInInfo (id, nombre, apellido, username, password, tipo)"
                         +  "VALUES("+id+",'"+primerNombre+"','"+apellido+"','"+username+"','"+password+"','"+tipo+"')";
 
                
                     
                statement.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Registro insertado con exito");
                cargarTabla();
                statement.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);

            }

        }

    }//GEN-LAST:event_btnInsertarBorrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        if(jTableUsuarios.getSelectionModel().isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "error");
        }else{

            int columna = 0;
            int fila = jTableUsuarios.getSelectedRow();
            String valor = jTableUsuarios.getModel().getValueAt(fila,columna).toString();
            int id = Integer.parseInt(valor);

            try{
                Statement statement  = conexion.conexionUsuarioDB().createStatement();
                String query = "DELETE FROM LogInInfo WHERE id="+id;

                statement.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Registro eliminado con exito");
                cargarTabla();
                statement.close();

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);

            }

        }

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jTableUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUsuariosMouseClicked
        // TODO add your handling code here:
        int fila = jTableUsuarios.getSelectedRow();
        String idEstudiante = jTableUsuarios.getModel().getValueAt(fila,0).toString();
        String primerNombre =jTableUsuarios.getModel().getValueAt(fila,1).toString();
        String apellido = jTableUsuarios.getModel().getValueAt(fila,2).toString();
        String username = jTableUsuarios.getModel().getValueAt(fila,3).toString();
        String password =jTableUsuarios.getModel().getValueAt(fila,4).toString();
        String tipo = jTableUsuarios.getModel().getValueAt(fila,5).toString();

        txtId.setText(idEstudiante);
        txtNombre.setText(primerNombre);
        txtApellido.setText(apellido);
        txtUsername.setText(username);
        txtPassword.setText(password);

        if (tipo.equals("Admin")) {
            cmbTipo.setSelectedIndex(1);
        } else if (tipo.equals("Cliente")) {
            cmbTipo.setSelectedIndex(2);
        } else if (tipo.equals("Empleado")) {
            cmbTipo.setSelectedIndex(3);
        } else if(tipo.equals("Visita")){
            cmbTipo.setSelectedIndex(4);
        }                   
    }//GEN-LAST:event_jTableUsuariosMouseClicked

    private void btnActualizarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarBorrarActionPerformed
               
         if(txtId.getText().isEmpty()||txtNombre.getText().isEmpty()||txtApellido.getText().isEmpty()||
           txtUsername.getText().isEmpty()||txtPassword.getText().isEmpty()||cmbTipo.getSelectedIndex()==0){
      
            JOptionPane.showMessageDialog(null, "error");
        }else{
                                  
                
                int id = Integer.parseInt(txtId.getText().trim());
                String primerNombre = txtNombre.getText().trim();
                String apellido = txtApellido.getText().trim();
                String username = txtUsername.getText().trim();            
                String password = txtPassword.getText().trim();
                String tipo =cmbTipo.getSelectedItem().toString().trim() ;
                
              try{
                    Statement statement  = conexion.conexionUsuarioDB().createStatement();
//                    String query = "UPDATE Proyecto.LogInInfo" +
//                                    "SET " +
//                                    "nombre = '"+primerNombre+"',"+
//                                    "apellido = '"+apellido+"',"+
//                                    "username = '"+username+"',"+
//                                    "password = '"+password+"',"+
//                                    "tipo ='"+tipo+"'"+
//                                    " WHERE id ="+id;
                   
                    String query = "UPDATE Proyecto.LogInInfo " +
                                   "SET " +
                                   "nombre = '"+primerNombre+"', " +
                                   "apellido = '"+apellido+"', " +
                                   "username = '"+username+"', " +
                                   "password = '"+password+"', " +
                                   "tipo = '"+tipo+"' " +
                                   "WHERE id = "+id;
                    
                    statement.executeUpdate(query);
                    JOptionPane.showMessageDialog(null, "Registro actualizado con exito");
                    cargarTabla();
                    statement.close();                                                    
                                   
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
                
        }   
               
                    
        }
        
    }//GEN-LAST:event_btnActualizarBorrarActionPerformed
      
    
    private void cargarTabla() {
        String query = "SELECT * FROM proyecto.logininfo";

        try {
            Statement statement = conexion.conexionUsuarioDB().createStatement();
            ResultSet resulset = statement.executeQuery(query);

            String[] columnas = {"id", "Nombre", "Apellido", "Nombre usuario", "Contraseña", "Tipo"};
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.setColumnIdentifiers(columnas);

            int id;
            String nombre;
            String apellido;
            String username;
            String password;
            String tipo;

            while (resulset.next()) {
                
                id = resulset.getInt("id");
                nombre = resulset.getString("nombre");
                apellido = resulset.getString("apellido");
                username = resulset.getString("username");
                password = resulset.getString("password");
                tipo = resulset.getString("tipo");
                modelo.addRow(new Object[]{id, nombre, apellido, username, password, tipo});
            }
            resulset.close();
            statement.close();
            jTableUsuarios.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

     
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnActualizarBorrar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnInsertarBorrar;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
